services:
  - type: web
    name: video-ai-webapp
    runtime: python
    rootDir: webapp
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-queue
          property: connectionString # التصحيح الأول

  - type: redis
    name: redis-queue

  - type: worker
    name: video-ai-worker
    runtime: docker # التصحيح الثاني
    dockerfilePath: ./Dockerfile
    plan: standard
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-queue
          property: connectionString # التصحيح الأول
